apiBaseUrl=http://localhost:80
apiVersion=/openmrs/ws/rest/v1
adminUsername=admin
adminPassword=Admin123
test_appointment_kind=Scheduled
test_appointment_create_status=Scheduled
test_appointment_update_status=CheckedIn
test_appointment_service_uuid=7ba3aa21-cc56-47ca-bb4d-a60549f666c0
test_location_uuid=44c3efb0-2583-4c80-a79e-1f756a03c0a1
test_order_care_setting=OUTPATIENT
test_lab_concept=ALKALINE_PHOSPHATASE
test_appointment_cancel_status=Cancelled
test_time_zone=+03:00

#UI
uiRemote = http://localhost:4444/wd/hub
uiBaseUrl = http://host.docker.internal/openmrs/spa
uiBrowser = chrome
uiBrowserSize = 1920x1080

