package apiParts.generators;

import com.github.javafaker.Faker;
import com.mifmif.common.regex.Generex;
import apiParts.models.VitalsConcept;
import apiParts.models.vitals.Obs;
import apiParts.steps.AdminSteps;
import apiParts.utils.DateTimeUtils;
import common.storages.SessionStorage;

import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.lang.reflect.ParameterizedType;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.*;
import java.util.concurrent.ThreadLocalRandom;

/**
 * Random test data.
 * <p>
 * Two ways to use it:
 * <ul>
 *     <li>{@link #generate(Class)} - whole model by reflection (all fields, including references);</li>
 *     <li>public random value methods below - single values for model builders, when references
 *     (uuid enums) must stay meaningful and only scalars are randomized.</li>
 * </ul>
 */
public class RandomModelGenerator {
    private static final Faker faker = new Faker();
    private static final int MAX_DEPTH = 3;

    // Bounds for fields generated by reflection without a generating rule
    private static final int DEFAULT_INT_MIN = 0;
    private static final int DEFAULT_INT_MAX = 1000;
    private static final int DEFAULT_DURATION_MIN = 1;
    private static final int DEFAULT_DURATION_MAX = 10;
    private static final long DEFAULT_LONG_MIN = 0L;
    private static final long DEFAULT_LONG_MAX = 100_000L;
    private static final double DEFAULT_DOUBLE_MIN = 0.0;
    private static final double DEFAULT_DOUBLE_MAX = 1000.0;
    private static final int DEFAULT_COLLECTION_MIN_SIZE = 1;
    private static final int DEFAULT_COLLECTION_MAX_SIZE = 3;
    private static final int LETTERS_IN_ALPHABET = 26;

    // Date range for @StartDateGeneratingRule / @EndDateGeneratingRule
    private static final int DATE_RANGE_START_MIN_DAYS_AGO = 1;
    private static final int DATE_RANGE_START_MAX_DAYS_AGO = 30;
    private static final int DATE_RANGE_MIN_MINUTES = 1;
    private static final int DATE_RANGE_MAX_MINUTES = 10 * 60;
    private static final String DATE_RANGE_START = "dateRangeStart";
    private static final String DATE_RANGE_END = "dateRangeEnd";
    private static final DateTimeFormatter OPENMRS_DATE_FORMAT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSZ");

    public static <T> T generate(Class<T> clazz) {
        return generate(clazz, new HashMap<>(), 0);
    }

    public static <T> T generate(Class<T> clazz, Map<String, Object> overrides) {
        return generate(clazz, overrides, 0);
    }

    private static Object generateIdentifierField(
            Field identifierField,
            Object instance
    ) {
        try {
            IdentifierGeneratingRule rule =
                    identifierField.getAnnotation(IdentifierGeneratingRule.class);

            Field typeField =
                    instance.getClass().getDeclaredField(rule.typeField());

            typeField.setAccessible(true);

            String identifierTypeUuid =
                    (String) typeField.get(instance);

            return IdentifierGenerator.generate(identifierTypeUuid);

        } catch (Exception e) {
            throw new RuntimeException(
                    "Failed to generate identifier for: "
                            + instance.getClass().getName(),
                    e
            );
        }
    }

    private static Object generateFromField(Field dependentField, Object instance) {
        DependsOnFieldGeneratingRule rule = dependentField.getAnnotation(DependsOnFieldGeneratingRule.class);
        try {
            Field sourceField = instance.getClass().getDeclaredField(rule.field());
            sourceField.setAccessible(true);
            Object source = sourceField.get(instance);

            return source == null ? null : source.getClass().getMethod(rule.valueMethod()).invoke(source);
        } catch (Exception e) {
            throw new RuntimeException(
                    "Failed to generate " + dependentField.getName() + " from field " + rule.field()
                            + " of " + instance.getClass().getName(),
                    e
            );
        }
    }

    private static <T> T generate(
            Class<T> clazz,
            Map<String, Object> overrides,
            int depth
    ) {
        if (depth > MAX_DEPTH) return null;

        try {
            T instance = createInstance(clazz);

            // Values shared between fields of this instance, e.g. start/end of a date range
            Map<String, Object> generated = new HashMap<>();

            // Сначала генерируем все поля,
            // кроме тех, которые зависят от других полей
            for (Field field : clazz.getDeclaredFields()) {
                // constants of the model (e.g. DrugOrder.SIMPLE_DOSING) are not data
                if (Modifier.isStatic(field.getModifiers())) {
                    continue;
                }
                field.setAccessible(true);

                if (overrides != null && overrides.containsKey(field.getName())) {
                    field.set(instance, overrides.get(field.getName()));
                    continue;
                }

                if (field.isAnnotationPresent(IgnoreGeneratingRule.class)) {
                    continue;
                }

                if (field.isAnnotationPresent(IdentifierGeneratingRule.class)
                        || field.isAnnotationPresent(DependsOnFieldGeneratingRule.class)) {
                    continue;
                }

                Object value = generateFieldValue(field, instance, generated, depth);
                field.set(instance, value);
            }

            // Теперь identifierType и другие поля уже заполнены,
            // поэтому можем генерировать зависящие от них identifier и @DependsOnFieldGeneratingRule
            for (Field field : clazz.getDeclaredFields()) {
                // constants of the model (e.g. DrugOrder.SIMPLE_DOSING) are not data
                if (Modifier.isStatic(field.getModifiers())) {
                    continue;
                }
                field.setAccessible(true);

                if (overrides != null && overrides.containsKey(field.getName())) {
                    continue;
                }

                if (field.isAnnotationPresent(IdentifierGeneratingRule.class)) {
                    field.set(instance, generateIdentifierField(field, instance));
                } else if (field.isAnnotationPresent(DependsOnFieldGeneratingRule.class)) {
                    field.set(instance, generateFromField(field, instance));
                }
            }

            return instance;

        } catch (Exception e) {
            throw new RuntimeException(
                    "Failed to generate model for: " + clazz.getName(),
                    e
            );
        }
    }

    // ======== RANDOM VALUES (for model builders in tests) ========

    /**
     * Random int in [minInclusive, maxInclusive], e.g. duration, numRefills.
     */
    public static int randomInt(int minInclusive, int maxInclusive) {
        requireRange(minInclusive, maxInclusive);
        return minInclusive == maxInclusive
                ? minInclusive
                : ThreadLocalRandom.current().nextInt(minInclusive, maxInclusive + 1);
    }

    /**
     * Random double in [min, max] rounded to {@code scale} decimal places, e.g. dose, quantity, obs value.
     * {@code scale = 0} gives a whole number.
     */
    public static double randomDouble(double min, double max, int scale) {
        requireRange(min, max);
        if (min == max) return round(min, scale);
        return round(ThreadLocalRandom.current().nextDouble(min, max), scale);
    }

    /**
     * Random negative double in [min, -step], where step is the smallest value at this precision
     * (scale = 1 -> -0.1, scale = 0 -> -1). Rounding never turns the result into 0.
     */
    public static double randomNegativeDouble(double min, int scale) {
        double step = 1 / Math.pow(10, scale);
        return randomDouble(min, -step, scale);
    }

    /**
     * Random negative int, e.g. invalid numRefills.
     */
    public static int randomNegativeInt(int min) {
        return randomInt(min, -1);
    }

    public static String randomWord() {
        return faker.lorem().word();
    }

    public static String randomWord(String word) {
        return faker.lorem().word();
    }

    /**
     * Free text for notes, dosingInstructions, etc.
     */
    public static String randomSentence() {
        return faker.lorem().sentence();
    }

    public static boolean randomBoolean() {
        return ThreadLocalRandom.current().nextBoolean();
    }

    /**
     * Random constant of an enum, e.g. BodySite, ProcedureStatus.
     */
    public static <E extends Enum<E>> E oneOf(Class<E> enumClass) {
        return oneOf(List.of(enumClass.getEnumConstants()));
    }

    /**
     * Random constant of an enum except the given ones, e.g. any DosingUnit but BOTTLE.
     */
    @SafeVarargs
    public static <E extends Enum<E>> E oneOfExcept(Class<E> enumClass, E... excluded) {
        List<E> allowed = new ArrayList<>(List.of(enumClass.getEnumConstants()));
        allowed.removeAll(List.of(excluded));
        return oneOf(allowed);
    }

    public static <T> T oneOf(List<T> values) {
        if (values == null || values.isEmpty()) {
            throw new IllegalArgumentException("Cannot pick a random value from an empty list");
        }
        return values.get(ThreadLocalRandom.current().nextInt(values.size()));
    }

    // ======== REFLECTION ========

    private static Object generateFieldValue(Field field, Object instance, Map<String, Object> generated, int depth) {
        Class<?> type = field.getType();

        DurationGeneratingRule durationGeneratingRule = field.getAnnotation(DurationGeneratingRule.class);
        if (durationGeneratingRule != null && (type.equals(int.class) || type.equals(Integer.class))) {
            return randomInt(DEFAULT_DURATION_MIN, DEFAULT_DURATION_MAX);
        }

        if (field.isAnnotationPresent(StartDateGeneratingRule.class) && type.equals(String.class)) {
            return dateRange(generated).get(DATE_RANGE_START);
        }

        if (field.isAnnotationPresent(EndDateGeneratingRule.class) && type.equals(String.class)) {
            return dateRange(generated).get(DATE_RANGE_END);
        }

        if (field.isAnnotationPresent(ProviderUuidGeneratingRule.class) && type.equals(String.class)) {
            return AdminSteps.getCurrentProviderUuid();
        }

        FixedStringGeneratingRule fixedStringRule = field.getAnnotation(FixedStringGeneratingRule.class);
        if (fixedStringRule != null && type.equals(String.class)) {
            return fixedStringRule.value();
        }

        PatientUuidGeneratingRule patientRule = field.getAnnotation(PatientUuidGeneratingRule.class);
        if (patientRule != null && type.equals(String.class)) {
            return SessionStorage.getPatient(patientRule.number()).getUuid();
        }

        if (field.isAnnotationPresent(VitalsObsGeneratingRule.class) && List.class.isAssignableFrom(type)) {
            return Arrays.stream(VitalsConcept.values()).map(Obs::random).toList();
        }

        StringGeneratingRule stringRule = field.getAnnotation(StringGeneratingRule.class);
        if (stringRule != null && !stringRule.regex().isEmpty() && type.equals(String.class)) {
            return generateFromRegex(stringRule.regex());
        }

        FixedEnumGeneratingRule fixedEnumRule =
                field.getAnnotation(FixedEnumGeneratingRule.class);

        if (fixedEnumRule != null && type.equals(String.class)) {
            return generateFixedEnum(fixedEnumRule);
        }

        // field of enum type (e.g. DrugOrder.careSetting): the constant itself, valueMethod is not used
        if (fixedEnumRule != null && type.isEnum()) {
            return Enum.valueOf(type.asSubclass(Enum.class), fixedEnumRule.value());
        }

        EnumGeneratingRule enumRule = field.getAnnotation(EnumGeneratingRule.class);
        if (enumRule != null && type.equals(String.class)) {
            return generateFromEnum(enumRule);
        }

        // field of enum type (e.g. DrugOrder.route): random constant itself, valueMethod is not used
        if (enumRule != null && type.isEnum()) {
            return oneOf(List.of(enumRule.enumClass().getEnumConstants()));
        }

        BooleanGeneratingRule booleanRule = field.getAnnotation(BooleanGeneratingRule.class);

        if (booleanRule != null && (type.equals(boolean.class) || type.equals(Boolean.class))) {
            return booleanRule.value();
        }

        DateGeneratingRule dateRule = field.getAnnotation(DateGeneratingRule.class);

        if (dateRule != null && type.equals(String.class)) {
            return generateDate(dateRule);
        }

        DateTimeGeneratingRule dateTimeRule =
                field.getAnnotation(DateTimeGeneratingRule.class);

        if (dateTimeRule != null && type.equals(String.class)) {
            return generateDateTime(dateTimeRule, instance);
        }

        DoubleGeneratingRule doubleRule = field.getAnnotation(DoubleGeneratingRule.class);
        if (doubleRule != null && (type.equals(double.class) || type.equals(Double.class))) {
            return randomDouble(doubleRule.min(), doubleRule.max(), doubleRule.range());
        }
        IntegerGeneratingRule integerRule = field.getAnnotation(IntegerGeneratingRule.class);
        if (integerRule != null && (type.equals(int.class) || type.equals(Integer.class))) {
            return randomInt(integerRule.min(), integerRule.max());
        }

        if (type.equals(String.class)) return randomWord();
        if (type.equals(int.class) || type.equals(Integer.class)) return defaultInt();
        if (type.equals(long.class) || type.equals(Long.class)) return defaultLong();
        if (type.equals(double.class) || type.equals(Double.class)) return defaultDouble();
        if (type.equals(boolean.class) || type.equals(Boolean.class)) return randomBoolean();
        if (type.equals(float.class) || type.equals(Float.class)) return randomFloat();
        if (type.equals(short.class) || type.equals(Short.class)) return (short) defaultInt();
        if (type.equals(byte.class) || type.equals(Byte.class)) return (byte) defaultInt();
        if (type.equals(char.class) || type.equals(Character.class)) return randomChar();

        if (type.isEnum()) {
            Object[] constants = type.getEnumConstants();
            return constants[ThreadLocalRandom.current().nextInt(constants.length)];
        }

        if (Collection.class.isAssignableFrom(type)) {
            return generateCollection(field, depth);
        }

        return generate(type, null, depth + 1);
    }

    private static Object generateCollection(Field field, int depth) {
        try {
            ParameterizedType genericType =
                    (ParameterizedType) field.getGenericType();

            Class<?> itemType =
                    (Class<?>) genericType.getActualTypeArguments()[0];

            CollectionGeneratingRule rule =
                    field.getAnnotation(CollectionGeneratingRule.class);

            int minSize = DEFAULT_COLLECTION_MIN_SIZE;
            int maxSize = DEFAULT_COLLECTION_MAX_SIZE;

            if (rule != null) {
                minSize = rule.minSize();
                maxSize = rule.maxSize();
            }

            List<Object> list = new ArrayList<>();

            int size = randomInt(minSize, maxSize);

            for (int i = 0; i < size; i++) {
                list.add(generate(itemType, null, depth + 1));
            }

            return list;

        } catch (Exception e) {
            return Collections.emptyList();
        }
    }

    private static Object generateFromRegex(String regex) {
        Generex generex = new Generex(regex);
        return generex.random();
    }

    private static String generateFromEnum(EnumGeneratingRule rule) {
        try {
            Enum<?>[] values = rule.enumClass().getEnumConstants();

            Enum<?> randomValue =
                    values[ThreadLocalRandom.current().nextInt(values.length)];

            return (String) rule.enumClass()
                    .getMethod(rule.valueMethod())
                    .invoke(randomValue);

        } catch (Exception e) {
            throw new RuntimeException(
                    "Failed to generate value from enum: "
                            + rule.enumClass().getName(),
                    e
            );
        }
    }

    private static String generateFixedEnum(FixedEnumGeneratingRule rule) {
        try {
            Enum<?> enumValue = Enum.valueOf(
                    rule.enumClass().asSubclass(Enum.class),
                    rule.value()
            );

            return (String) rule.enumClass()
                    .getMethod(rule.valueMethod())
                    .invoke(enumValue);

        } catch (Exception e) {
            throw new RuntimeException(
                    "Failed to generate fixed enum value: "
                            + rule.enumClass().getName()
                            + "." + rule.value(),
                    e
            );
        }
    }


    /**
     * Start/end pair, generated once per model instance and put into {@code generated}:
     * start - random minute 1..30 days ago, end - start + 1 minute..10 hours.
     * Both are in the past, truncated to minutes (server does not store milliseconds).
     */
    private static Map<String, Object> dateRange(Map<String, Object> generated) {
        if (!generated.containsKey(DATE_RANGE_START)) {
            OffsetDateTime start = DateTimeUtils.now()
                    .minusDays(randomInt(DATE_RANGE_START_MIN_DAYS_AGO, DATE_RANGE_START_MAX_DAYS_AGO))
                    .minusMinutes(randomInt(0, 24 * 60 - 1));
            OffsetDateTime end = start.plusMinutes(randomInt(DATE_RANGE_MIN_MINUTES, DATE_RANGE_MAX_MINUTES));

            generated.put(DATE_RANGE_START, start.format(DateTimeUtils.OPENMRS_REQUEST_DATE_TIME));
            generated.put(DATE_RANGE_END, end.format(DateTimeUtils.OPENMRS_REQUEST_DATE_TIME));
        }
        return generated;
    }

    private static String generateDate(DateGeneratingRule rule) {
        LocalDate start = LocalDate.of(rule.minYear(), 1, 1);
        LocalDate end = LocalDate.of(rule.maxYear(), 12, 31);

        long daysBetween = ChronoUnit.DAYS.between(start, end);

        LocalDate randomDate = start.plusDays(
                ThreadLocalRandom.current().nextLong(daysBetween + 1)
        );

        return randomDate
                .atStartOfDay()
                .atOffset(ZoneOffset.UTC)
                .format(OPENMRS_DATE_FORMAT);
    }

    private static String generateDateTime(
            DateTimeGeneratingRule rule,
            Object instance
    ) {
        try {
            OffsetDateTime dateTime;

            if (!rule.baseField().isEmpty()) {
                Field baseField =
                        instance.getClass().getDeclaredField(rule.baseField());

                baseField.setAccessible(true);

                String baseValue = (String) baseField.get(instance);

                dateTime = OffsetDateTime.parse(
                        baseValue,
                        OPENMRS_DATE_FORMAT
                ).plusMinutes(rule.minutesFromBase());

            } else {
                dateTime = OffsetDateTime.now(ZoneOffset.UTC)
                        .plusMinutes(rule.minutesFromNow());
            }

            return dateTime
                    .withNano(0)
                    .format(OPENMRS_DATE_FORMAT);

        } catch (Exception e) {
            throw new RuntimeException(
                    "Failed to generate date-time for field",
                    e
            );
        }
    }

    public static String futureDateTime() {
        return LocalDateTime.now()
                .plusYears(1)
                .atOffset(ZoneOffset.UTC)
                .format(OPENMRS_DATE_FORMAT);
    }

    public static String pastDateTime() {
        return LocalDateTime.now()
                .minusYears(1)
                .withNano(0)
                .atOffset(ZoneOffset.UTC)
                .format(OPENMRS_DATE_FORMAT);
    }

    private static <T> T createInstance(Class<T> clazz) throws Exception {
        Constructor<T> constructor = clazz.getDeclaredConstructor();
        constructor.setAccessible(true);
        return constructor.newInstance();
    }

    // ======== HELPERS ========
    private static double round(double value, int scale) {
        double factor = Math.pow(10, scale);
        return Math.round(value * factor) / factor;
    }

    private static void requireRange(double min, double max) {
        if (min > max) {
            throw new IllegalArgumentException("min must be <= max, but was " + min + ".." + max);
        }
    }

    private static int defaultInt() {
        return randomInt(DEFAULT_INT_MIN, DEFAULT_INT_MAX);
    }

    private static long defaultLong() {
        return ThreadLocalRandom.current().nextLong(DEFAULT_LONG_MIN, DEFAULT_LONG_MAX);
    }

    private static double defaultDouble() {
        return ThreadLocalRandom.current().nextDouble(DEFAULT_DOUBLE_MIN, DEFAULT_DOUBLE_MAX);
    }

    private static float randomFloat() {
        return ThreadLocalRandom.current().nextFloat();
    }

    private static char randomChar() {
        return (char) (ThreadLocalRandom.current().nextInt(LETTERS_IN_ALPHABET) + 'a');
    }
}
